============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.3.1, pluggy-1.0.0
rootdir: /data/sandeep/leetcode-master/.verifaiws
collected 1 item

293_Flip_Game/test_293_Flip_Game.py F                                    [100%]

=================================== FAILURES ===================================
______________________ test_generate_possible_next_moves _______________________

    def test_generate_possible_next_moves():
        solution = Solution()
    
        s1 = "++"
        actual_output1 = solution.generatePossibleNextMoves(s1)
        expected_output1 = ["--"]
        assert actual_output1 == expected_output1
    
        s2 = "+-+-"
        actual_output2 = solution.generatePossibleNextMoves(s2)
        expected_output2 = []
        assert actual_output2 == expected_output2
    
        s3 = ""
        actual_output3 = solution.generatePossibleNextMoves(s3)
        expected_output3 = []
        assert actual_output3 == expected_output3
    
        s4 = "++++"
        actual_output4 = solution.generatePossibleNextMoves(s4)
        expected_output4 = ["--++", "+--+" ,"++--"]
        assert actual_output4 == expected_output4
    
        s5 = "++-+"
        actual_output5 = solution.generatePossibleNextMoves(s5)
        expected_output5 = ["--+", "+--"]
>       assert actual_output5 == expected_output5
E       AssertionError: assert ['---+'] == ['--+', '+--']
E         At index 0 diff: '---+' != '--+'
E         Right contains one more item: '+--'
E         Use -v to get more diff

293_Flip_Game/test_293_Flip_Game.py:30: AssertionError
=========================== short test summary info ============================
FAILED 293_Flip_Game/test_293_Flip_Game.py::test_generate_possible_next_moves
============================== 1 failed in 0.01s ===============================
