============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.3.1, pluggy-1.0.0
rootdir: /data/sandeep/leetcode-master/.verifaiws
collected 1 item

092_Reverse_Linked_Lis_ II/test_092_Reverse_Linked_Lis_ II.py F          [100%]

=================================== FAILURES ===================================
_______________________ TestSolution.test_reverseBetween _______________________

self = <test_092_Reverse_Linked_Lis_ II.TestSolution object at 0x7fb5299ac3d0>

    def test_reverseBetween(self):
>       solution = Solution()
E       NameError: name 'Solution' is not defined

092_Reverse_Linked_Lis_ II/test_092_Reverse_Linked_Lis_ II.py:34: NameError
=========================== short test summary info ============================
FAILED 092_Reverse_Linked_Lis_ II/test_092_Reverse_Linked_Lis_ II.py::TestSolution::test_reverseBetween
============================== 1 failed in 0.01s ===============================
